# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: general.tabTitle #German Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: staging
remote_data_prefix: "https://mobosse.github.io/data-starter"
# URL for the "Edit Data" button on indicators.
data_edit_url: http://prose.io/#mobosse/data-starter/edit/develop/data/indicator_[id].csv
# URL for the "Edit Metadata" button on indicators.
metadata_edit_url: http://prose.io/#mobosse/data-starter/edit/develop/meta/[id].md
# permalink: /news/:year/:month/:day/:title.html


# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal-by-target
  previous_next_links: false

create_pages: true

frontpage_goals_grid:
    title: frontpage.heading
    description: frontpage.instructions

frontpage_cards:
    - rule_color: orange
      title: ''
      include: components/download-all-data.html

analytics:
  ga_prod: ''

###################################################################################################
email_contacts:
  questions: sdg-indicators@destatis.de
  suggestions: sdg-indicators@destatis.de
  functional: sdg-indicators@destatis.de
###################################################################################################


# Build settings
markdown: kramdown

exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE


# International Support
# Eg name: Australia and adjective: Australian.
country:
  name: Germany
  adjective: German

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# The list of languages that are translated. The first one is the default.
languages:
  - es
  - en

# Menu
menu:
  - path: /
    translation_key: general.seventeen_goals
  - path: https://dns-indikatoren.de
    translation_key: menu.linkToDnsPlatform


contrast_type: single

header_language_toggle: links
header:
    include: header-default.html

footer_menu:
  - path: 'mailto:sdg-indicators@destatis.de'
    translation_key: menu.contact_us


# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

search_index_extra_fields:
  #- indicator_number
  - national_indicator_available
  - indicator_name
  - target_name
  - target_id
  - data_keywords
  - graph_title


series_toggle: true
graph_title_from_series: true
decimal_separator: ','
thousands_separator: ' '
graph_color_headline: '#b8b8b8' #
#graph_color_headline: ['#e5243b', '#dda63a', '#4c9f38', '#c5192d', '#ff3a21', '#26bde2', '#fcc30b', '#a21942', '#fd6925', '#dd1367', '#fd9d24', '#bf8b2e', '#3f7e44', '#0a97d9', '#56c02b', '#00689d', '#19486a']
useHeadlineColor: false
no_value_character: '.'

reporting_status:
    title: status.reporting_status
    description: status.status_blurb
    disaggregation_tabs: false

hide_empty_metadata: true
hide_single_unit: true

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins


# Use a remote Jekyll theme.
#remote_theme: brockfanning/open-sdg@map-series-unit-behaviors
remote_theme: open-sdg/open-sdg@2.2.0


#remote_theme: brockfanning/open-sdg@goal-page-status-css
goal_image_base: https://g205sdgs.github.io/sdg-indicators/assets/img/goals

accessible_tabs: true
accessible_charts: true

custom_js:
  - /assets/js/custom.js

graph_color_set: 'goal'
graph_color_number: 9

disclaimer:
  phase: beta

# Mapping
map_options:
  disaggregation_controls: true

  # Control the limits on zooming in/out in the map:
  minZoom: 5
  maxZoom: 10
  # If you would like to use tile (background) imagery, use these:
  tileURL: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
  tileOptions:
    id: mapbox.light
    accessToken: pk.eyJ1IjoibW9ib3NzZSIsImEiOiJjazU1M2trazQwYnFwM2trYmdwNm9rOWxkIn0.u36w-RJPqoTGmivl_zED1w
    attribution: <a href="https://www.openstreetmap.org/copyright">&copy; OpenStreetMap</a> contributors |<br class="visible-xs"> <a href="https://www.bkg.bund.de">&copy; GeoBasis-De / BKG 2023</a> |<br class="hidden-lg"> <a href="https://www.destatis.de/DE/Home/_inhalt.html">&copy; Statistisches Bundesamt (Destatis), 2023</a>
  # Control the choropleth color range. See https://gka.github.io/chroma.js/#chroma-brewer
  # 1 map color depending on goal --- start ---
  colorRange: ["#F6E8EC", "#E3BAC6", "#D18CA1", "#BE5E7B", "#AB3055", "#A21942", "#821435", "#610F28", "#410A1A", "#20050D"]

  # Set the color for boundaries that have no data.
  noValueColor: '#f0f0f0'
  # For documentation on the style options below, see here:
  # https://leafletjs.com/reference-1.4.0.html#path-option
  # Set the default style for boundaries in the map:
  styleNormal:
    weight: 1
    opacity: 1
    color: '#888'
    fillOpacity: 0.7
  # Set the style for boundaries that have been selected/highlighted:
  styleHighlighted:
    weight: 1
    opacity: 1
    color: '#111'
    fillOpacity: 0.7
  # Set the style for top-level boundaries that are displaying in other layers.
  # Note: This is only applicable when using the "nested zoom" feature (see below).
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: 5,5

map_layers:
  - serviceUrl:  https://sdgtestenvironment.github.io/dns-indicators/assets/maps/boundaries.geojson
    min_zoom: 4.5
    max_zoom: 6.5
    staticBorders: true
    subfolder: laender
    label: indicator.map
  - serviceUrl:  https://sdgtestenvironment.github.io/dns-indicators/assets/maps/boundariesKrs.geojson
    min_zoom: 7
    max_zoom: 11
    staticBorders: false
    subfolder: kreise
    label: indicator.map

progressive_web_app:
  enabled: true
  name: SDG Indikatoren für Deutschland
  short_name: SDGs Deutschland
  precaching: true

proxy_indicators:
  label: Proxy
  description: Diese Zeitreihe entspricht nicht den globalen Metadaten

